# image: java:8

test:
  stage: test
  # image: enzief/egreen-ci:sbt-1.2.8
  image: hseeberger/scala-sbt
  script:
    - sbt clean test
    # - sbt clean coverage test coverageReport
  cache:
    key: "$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
    untracked: true
    paths:
      - "sbt-cache/.ivy/cache"
      - "sbt-cache/.boot"
      - "sbt-cache/.sbtboot"
      - "sbt-cache/target"